var EVENT_SINGNATUR = {
	'GCopyrightCollection':{
		'newcopyright'
			:['newcopyright',['GCopyright']]
	},
	'GDirections':{
		'load'
			:['load',[]],
		'addoverlay'
			:['addoverlay',[]],
		'error'
			:['error',[]]
	},
	'GDraggableObject':{
		'mousedown'
			:['mousedown',[]],
		'mouseup'
			:['mouseup',[]],
		'click'
			:['click',[]],
		'dragstart'
			:['dragstart',[]],
		'drag'
			:['drag',[]],
		'dragend'
			:['dragend',[]]
	},
	'GEvent':{
		'clearlisteners'
			:['clearlisteners',['String']]
	},
	'GGeoXml':{
		'load'
			:['load',[]]
	},
	'GGroundOverlay':{
		'visibilitychanged'
			:['visibilitychanged',['Boolean']]
	},
	'GInfoWindow':{
		'closeclick'
			:['closeclick',[]],
		'maximizeclick'
			:['maximizeclick',[]],
		'maximizeend'
			:['maximizeend',[]],
		'restoreclick'
			:['restoreclick',[]],
		'restoreend'
			:['restoreend',[]]
	},
	'GMap2':{
		'addmaptype'
			:['addmaptype',['GMapType']],
		'removemaptype'
			:['removemaptype',['GMapType']],
		'click'
			:['click',['GOverlay','GLatLng','GLatLng']],
		'dblclick'
			:['dblclick',['GOverlay','GLatLng']],
		'singlerightclick'
			:['singlerightclick',['GPoint','Element','GOverlay']],
		'movestart'
			:['movestart',[]],
		'move'
			:['move',[]],
		'moveend'
			:['moveend',[]],
		'zoomend'
			:['zoomend',['Number','Number']],
		'maptypechanged'
			:['maptypechanged',[]],
		'infowindowopen'
			:['infowindowopen',[]],
		'infowindowbeforeclose'
			:['infowindowbeforeclose',[]],
		'infowindowclose'
			:['infowindowclose',[]],
		'addoverlay'
			:['addoverlay',['GOverlay']],
		'removeoverlay'
			:['removeoverlay',['GOverlay']],
		'clearoverlays'
			:['clearoverlays',[]],
		'mouseover'
			:['mouseover',['GLatLng']],
		'mouseout'
			:['mouseout',['GLatLng']],
		'mousemove'
			:['mousemove',['GLatLng']],
		'dragstart'
			:['dragstart',[]],
		'drag'
			:['drag',[]],
		'dragend'
			:['dragend',[]],
		'load'
			:['load',[]],
		'tilesloaded'
			:['tilesloaded',[]],
		'headingchanged'
			:['headingchanged',[]],
		'rotatabilitychanged'
			:['rotatabilitychanged',[]]
	},
	'GMapType':{
		'newcopyright'
			:['newcopyright',['GCopyright']]
	},
	'GMarker':{
		'click'
			:['click',['GLatLng']],
		'dblclick'
			:['dblclick',['GLatLng']],
		'mousedown'
			:['mousedown',['GLatLng']],
		'mouseup'
			:['mouseup',['GLatLng']],
		'mouseover'
			:['mouseover',['GLatLng']],
		'mouseout'
			:['mouseout',['GLatLng']],
		'infowindowopen'
			:['infowindowopen',[]],
		'infowindowbeforeclose'
			:['infowindowbeforeclose',[]],
		'infowindowclose'
			:['infowindowclose',[]],
		'remove'
			:['remove',[]],
		'dragstart'
			:['dragstart',['GLatLng']],
		'drag'
			:['drag',['GLatLng']],
		'dragend'
			:['dragend',['GLatLng']],
		'visibilitychanged'
			:['visibilitychanged',['Boolean']]
	},
	'GPolygon':{
		'remove'
			:['remove',[]],
		'visibilitychanged'
			:['visibilitychanged',['Boolean']],
		'click'
			:['click',['GLatLng']],
		'mouseover'
			:['mouseover',[]],
		'mouseout'
			:['mouseout',[]],
		'lineupdated'
			:['lineupdated',[]],
		'endline'
			:['endline',[]],
		'cancelline'
			:['cancelline',[]]
	},
	'GPolyline':{
		'remove'
			:['remove',[]],
		'visibilitychanged'
			:['visibilitychanged',['Boolean']],
		'click'
			:['click',['GLatLng']],
		'mouseover'
			:['mouseover',[]],
		'mouseout'
			:['mouseout',[]],
		'lineupdated'
			:['lineupdated',[]],
		'endline'
			:['endline',[]],
		'cancelline'
			:['cancelline',[]]
	},
	'GScreenOverlay':{
		'visibilitychanged'
			:['visibilitychanged',['Boolean']]
	},
	'GStreetviewOverlay':{
		'changed'
			:['changed',['Boolean']]
	},
	'GStreetviewPanorama':{
		'yawchanged'
			:['yawchanged',['Number']],
		'pitchchanged'
			:['pitchchanged',['Number']],
		'zoomchanged'
			:['zoomchanged',['Number']],
		'error'
			:['error',['GStreetviewPanorama.ErrorValues']],
		'initialized'
			:['initialized',['GStreetviewLocation']],
		'initialized'
			:['initialized',['GStreetviewLocation']]
	},
	'GTileLayer':{
		'newcopyright'
			:['newcopyright',['GCopyright']]
	},
	'GTrafficOverlay':{
		'changed'
			:['changed',['Boolean']]
	}
};//GCopyright,String,Boolean,GMapType,GOverlay,GLatLng,GPoint,Element,Number,GStreetviewPanorama.ErrorValues,GStreetviewLocation