addmaptype(type:GMapType)
removemaptype(type:GMapType)
click(overlay:GOverlay, latlng:GLatLng, overlaylatlng:GLatLng)
dblclick(overlay:GOverlay, latlng:GLatLng)
singlerightclick(point:GPoint, src:Element, overlay?:GOverlay)
movestart()
move()
moveend()
zoomend(oldLevel:Number, newLevel:Number)
maptypechanged()
infowindowopen()
infowindowbeforeclose()
infowindowclose()
addoverlay(overlay:GOverlay)
removeoverlay(overlay:GOverlay)
clearoverlays()
mouseover(latlng:GLatLng)
mouseout(latlng:GLatLng)
mousemove(latlng:GLatLng)
dragstart()
drag()
dragend()
load()
tilesloaded()
headingchanged()
rotatabilitychanged()
